
export interface CreditCardSeed {
    name: string
    type: string
    number: string
    expiry: string
    cvv: string
    limit: number
    statementDate: string | number
    paymentDate: string
    annualFee: number
    renewalMonth: string
    waveOffLimit: number
    cashback: string
    rewardPoints: string
    rpValue: number
    rpExpiryMonths: number | string
    rpLimit: string
    partners: string
    loungeNational: string
    loungeInternational: string
    railwayLounge: string
}

export const initialCards: CreditCardSeed[] = [
    {
        name: 'SBI BPCL',
        type: 'VISA',
        number: '4611199394936358',
        expiry: '02/26', // Derived from '226' -> Feb 26
        cvv: '429',
        limit: 34000,
        statementDate: 12, // '12 Aug' -> 12
        paymentDate: '20 Aug', // Keeps string for reference or parse day? Let's use string for now or '20'
        annualFee: 499,
        renewalMonth: 'Feb',
        waveOffLimit: 100000,
        cashback: '4.25% on fuel at BPCL',
        rewardPoints: '5X on groceries, dining',
        rpValue: 0.25,
        rpExpiryMonths: 24,
        rpLimit: 'Max 1300 RP per billing cycle',
        partners: 'BPCL',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'SBI Paytm',
        type: 'VISA',
        number: '4129470904684092',
        expiry: '05/29', // '529' -> May 29
        cvv: '963',
        limit: 150000,
        statementDate: 18,
        paymentDate: '6 July',
        annualFee: 500,
        renewalMonth: 'Feb',
        waveOffLimit: 100000,
        cashback: '3% on Paytm Mall, movies, travel',
        rewardPoints: '1% elsewhere',
        rpValue: 0.25,
        rpExpiryMonths: 24,
        rpLimit: 'Capped at ₹100 per statement cycle',
        partners: 'Paytm Mall',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'SBI Simply save',
        type: 'MASTERCARD',
        number: '5241828335115905',
        expiry: '08/26', // '826'
        cvv: '948',
        limit: 16000,
        statementDate: 9,
        paymentDate: '28 Mar',
        annualFee: 499,
        renewalMonth: '',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: '10X on dining, movies, groceries',
        rpValue: 0.25,
        rpExpiryMonths: 24,
        rpLimit: 'Max 10,000 RP per month',
        partners: 'Dining, movies, groceries',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'SC EaseMyTrip',
        type: 'VISA',
        number: '4940777670885621',
        expiry: '09/28', // '928'
        cvv: '536',
        limit: 214500,
        statementDate: 11,
        paymentDate: '2 Nov',
        annualFee: 350,
        renewalMonth: 'Oct',
        waveOffLimit: 50000,
        cashback: '20% on hotels, 10% on flights',
        rewardPoints: '10X on hotel/flight bookings',
        rpValue: 0.5,
        rpExpiryMonths: 24,
        rpLimit: 'Max discount ₹5000 hotels',
        partners: 'EaseMyTrip',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'Axis My Zone',
        type: 'VISA',
        number: '4514570059089170',
        expiry: '10/27', // '1027'
        cvv: '043', // 'o43' -> 043 typo likely
        limit: 154000,
        statementDate: 13,
        paymentDate: '30 July',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: '2% on daily spends',
        rewardPoints: '1X on daily spends',
        rpValue: 0.25,
        rpExpiryMonths: 36,
        rpLimit: 'Max discount ₹1000 on Swiggy',
        partners: 'Swiggy, AJIO',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'Axis Neo',
        type: 'VISA',
        number: '4641180019364980',
        expiry: '05/27',
        cvv: '916',
        limit: 154000,
        statementDate: 18,
        paymentDate: '5 Aug',
        annualFee: 250,
        renewalMonth: 'May',
        waveOffLimit: 0,
        cashback: '2.5% on dining, movies',
        rewardPoints: '1X on dining',
        rpValue: 0.25,
        rpExpiryMonths: 36,
        rpLimit: 'NA',
        partners: 'Zomato, Blinkit',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'RBL Platinum Delight',
        type: 'VISA',
        number: '4391230231957087',
        expiry: '07/31',
        cvv: '668',
        limit: 224000,
        statementDate: 12,
        paymentDate: '2 Sep',
        annualFee: 1000,
        renewalMonth: 'Feb',
        waveOffLimit: 200000,
        cashback: 'NA',
        rewardPoints: '2X weekdays, 4X weekends',
        rpValue: 0.25,
        rpExpiryMonths: 24,
        rpLimit: 'Fuel surcharge waiver',
        partners: 'Shopping',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'RBL Bajaj Finserv',
        type: 'VISA',
        number: '4391230898849635',
        expiry: '02/30',
        cvv: '946',
        limit: 160000,
        statementDate: 12,
        paymentDate: '2 Sep',
        annualFee: 1000,
        renewalMonth: 'Dec',
        waveOffLimit: 200000,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'Airport lounges',
        loungeNational: 'Yes',
        loungeInternational: 'Yes',
        railwayLounge: 'NA'
    },
    {
        name: 'HDFC Millenia',
        type: 'DISCOVER',
        number: '36113573131470',
        expiry: '06/28',
        cvv: '864',
        limit: 10000,
        statementDate: 19,
        paymentDate: '7 Jan',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: '5% on select online',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 24,
        rpLimit: 'Fuel surcharge waiver',
        partners: 'Amazon, Flipkart, Swiggy',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'HDFC Neu',
        type: 'RUPAY',
        number: '6529250009245556',
        expiry: '08/31',
        cvv: '644',
        limit: 10000,
        statementDate: 2,
        paymentDate: '21 Feb',
        annualFee: 499,
        renewalMonth: 'Sep',
        waveOffLimit: 0,
        cashback: '5% on Tata',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 24,
        rpLimit: 'NA',
        partners: 'Tata Neu, BigBasket',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'Indusind Platinum Aura Edge',
        type: 'VISA',
        number: '4412859670930976',
        expiry: '01/28',
        cvv: '750',
        limit: 151000,
        statementDate: 13,
        paymentDate: '2 July',
        annualFee: 0,
        renewalMonth: '',
        waveOffLimit: 0,
        cashback: 'Up to 4 RP',
        rewardPoints: '0.5 RP elsewhere',
        rpValue: 0.25,
        rpExpiryMonths: 24,
        rpLimit: 'Max 2500 RP per month',
        partners: 'Amazon, Flipkart',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'Indusind Rupay',
        type: 'RUPAY',
        number: '3561420006556273',
        expiry: '09/29',
        cvv: '755',
        limit: 100000,
        statementDate: 1, // Missing
        paymentDate: '',
        annualFee: 0,
        renewalMonth: '',
        waveOffLimit: 0,
        cashback: '1% non-UPI',
        rewardPoints: '2 RP on UPI',
        rpValue: 0.6,
        rpExpiryMonths: 24,
        rpLimit: 'NA',
        partners: 'UPI',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'ICICI Amazon',
        type: 'RUPAY',
        number: '4315812748438017',
        expiry: '03/32',
        cvv: '954',
        limit: 460000,
        statementDate: 18,
        paymentDate: '5 Aug',
        annualFee: 0,
        renewalMonth: '',
        waveOffLimit: 0,
        cashback: '5% on Amazon',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'No Expiry',
        rpLimit: 'NA',
        partners: 'Amazon',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'ICICI Adani One',
        type: 'VISA',
        number: '4786723001037026',
        expiry: '02/32',
        cvv: '241',
        limit: 1,
        statementDate: 5,
        paymentDate: '23 Aug',
        annualFee: 0,
        renewalMonth: 'Feb',
        waveOffLimit: 50000,
        cashback: 'NA',
        rewardPoints: '2X Adani',
        rpValue: 0.25,
        rpExpiryMonths: 'No Expiry',
        rpLimit: 'NA',
        partners: 'Adani',
        loungeNational: 'Yes',
        loungeInternational: 'Yes',
        railwayLounge: 'NA'
    },
    {
        name: 'Pop YES Bank',
        type: 'JCB',
        number: '3561395211379572',
        expiry: '01/32',
        cvv: '095',
        limit: 300000,
        statementDate: 16,
        paymentDate: '5 Sep',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: '2 POPcoins',
        rpValue: 0.25,
        rpExpiryMonths: 36,
        rpLimit: 'NA',
        partners: 'Various',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'SuperMoney',
        type: 'RUPAY',
        number: '3561241060899296',
        expiry: '09/32',
        cvv: '553',
        limit: 1800,
        statementDate: 1,
        paymentDate: '5 Oct',
        annualFee: 0,
        renewalMonth: 'Sep',
        waveOffLimit: 0,
        cashback: '1% UPI',
        rewardPoints: '',
        rpValue: 0,
        rpExpiryMonths: '',
        rpLimit: '',
        partners: 'UPI',
        loungeNational: '',
        loungeInternational: '',
        railwayLounge: ''
    },
    {
        name: 'BAJAJ Finserv EMI',
        type: 'EMI',
        number: '2030403213037910',
        expiry: '10/22',
        cvv: '',
        limit: 115000,
        statementDate: 1,
        paymentDate: '15th',
        annualFee: 0,
        renewalMonth: '',
        waveOffLimit: 0,
        cashback: '',
        rewardPoints: '',
        rpValue: 0,
        rpExpiryMonths: '',
        rpLimit: '',
        partners: '',
        loungeNational: '',
        loungeInternational: '',
        railwayLounge: ''
    },
    {
        name: 'Axis Rewards',
        type: 'VISA',
        number: '5521370103599086',
        expiry: '03/30',
        cvv: '046',
        limit: 120000,
        statementDate: 21,
        paymentDate: '08 Apr',
        annualFee: 1000,
        renewalMonth: 'Feb',
        waveOffLimit: 30000,
        cashback: '2.5% on dining, movies',
        rewardPoints: '1X on dining',
        rpValue: 0.25,
        rpExpiryMonths: 36,
        rpLimit: 'NA',
        partners: 'Dining, movies, groceries',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'CBI',
        type: 'RUPAY',
        number: '6522810011012802',
        expiry: '05/28',
        cvv: '739',
        limit: 1,
        statementDate: 1,
        paymentDate: '',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'NA',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'SBI',
        type: 'RUPAY',
        number: '6522940910754350',
        expiry: '01/28',
        cvv: '741',
        limit: 1,
        statementDate: 1,
        paymentDate: '',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'NA',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'Jupiter',
        type: 'VISA',
        number: '4481980040929534',
        expiry: '11/27',
        cvv: '001',
        limit: 1,
        statementDate: 1,
        paymentDate: '',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'NA',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'Slice',
        type: 'RUPAY',
        number: '8180280001295685',
        expiry: '08/28',
        cvv: '458',
        limit: 1,
        statementDate: 1,
        paymentDate: '',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'NA',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'Tide',
        type: 'RUPAY',
        number: '5086371014734595',
        expiry: '09/29',
        cvv: '310',
        limit: 1,
        statementDate: 1,
        paymentDate: '',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'NA',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'SBM',
        type: 'VISA',
        number: '4645160105982636',
        expiry: '06/99',
        cvv: '728',
        limit: 1,
        statementDate: 1,
        paymentDate: '',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'NA',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    },
    {
        name: 'DCB',
        type: 'VISA',
        number: '4346720003350178',
        expiry: '03/32',
        cvv: '923',
        limit: 1,
        statementDate: 1,
        paymentDate: '',
        annualFee: 0,
        renewalMonth: 'NA',
        waveOffLimit: 0,
        cashback: 'NA',
        rewardPoints: 'NA',
        rpValue: 0,
        rpExpiryMonths: 'NA',
        rpLimit: 'NA',
        partners: 'NA',
        loungeNational: 'NA',
        loungeInternational: 'NA',
        railwayLounge: 'NA'
    }
]
