export const EXPENSE_CATEGORIES = {
    Loan: ['Education loan'],
    Transport: ['Travel', 'Petrol'],
    Car: ['Car Insurance', 'Car Pollution Certificate'],
    Telecomm: ['Data', 'Jio', 'Airtel', 'WiFi'],
    'Self Growth': ['Books'],
    Food: [
        'Eating out',
        'Swiggy',
        'Groceries',
        'Dry fruits',
        'Vegetables',
        'Fruits',
        'Snacks',
    ],
    Grooming: ['Haircut', 'Toiletries'],
    Health: [
        'Fitness bootcamp',
        'Chef',
        'Yoga instructor',
        'Supliments + Vitamins',
        'Medicine',
    ],
    Clothing: ['Clothing'],
    Insurance: ['Medical Insurance', 'Life Insurance'],
    Subscriptions: ['Google one', 'Youtube', 'Grok', 'LinkedIn Premium'],
    'Credit Card Monthly': [
        'SBI BPCL MP',
        'SBI Paytm MP',
        'SBI Simply save MP',
        'SC EaseMyTrip MP',
        'Axis My Zone MP',
        'Axis Neo MP',
        'RBL Platinum Delight MP',
        'RBL Bajaj Finserv MP',
        'HDFC Millenia MP',
        'HDFC Neu MP',
        'Indusind Platinum Aura Edge MP',
        'Indusind Rupay MP',
        'ICICI Amazon MP',
        'ICICI Adani One MP',
        'Pop YES Bank MP',
    ],
    'Credit Card EMI': [
        'SBI BPCL EMI',
        'SBI Paytm EMI',
        'SBI Simply save EMI',
        'SC EaseMyTrip EMI',
        'Axis My Zone EMI',
        'Axis Neo EMI',
        'RBL Platinum Delight EMI',
        'RBL Bajaj Finserv EMI',
        'HDFC Millenia EMI',
        'HDFC Neu EMI',
        'Indusind Platinum Aura Edge EMI',
        'Indusind Rupay EMI',
        'ICICI Amazon EMI',
        'ICICI Adani One EMI',
        'Pop YES Bank EMI',
    ],
    'Pay Later': ['Simpl', 'Lazypay', 'Amazon Pay'],
    Misc: ['Amazon Pay Recharge', 'Supplement', 'Shopping', 'Miscellaneous'],
}

// Helper to get flattened list for dropdowns if needed
export const FLATTENED_CATEGORIES = Object.entries(EXPENSE_CATEGORIES).flatMap(
    ([group, items]) => items.map((item) => `${group}: ${item}`)
)
