import { financeManager } from './supabaseDataManager'

export async function generateDailySummary(userId: string) {
    // 1. Fetch all data in parallel
    const [liquidity, loans, cards, goals] = await Promise.all([
        financeManager.getLiquidityData(),
        financeManager.getLoans(),
        financeManager.getCreditCards(),
        financeManager.getGoals()
    ])

    // 2. Calculations
    const totalAssets = liquidity.totalLiquidity

    const totalLoanOutstanding = loans.reduce((sum, l) => sum + (l.current_balance || 0), 0)
    const totalCCOutstanding = cards.reduce((sum, c) => sum + (c.current_balance || 0), 0)
    const totalLiabilities = totalLoanOutstanding + totalCCOutstanding

    const netWorth = totalAssets - totalLiabilities

    const currentMonthEmis = loans
        .filter(l => l.type === 'EMI' && l.is_active)
        .reduce((sum, l) => sum + (l.emi_amount || 0), 0)

    // 3. Formatting
    const formatMoney = (amount: number) =>
        new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount)

    const emailHtml = `
    <h1>Daily Financial Summary</h1>
    <p><strong>Date:</strong> ${new Date().toLocaleDateString('en-IN')}</p>
    
    <h2>💰 Net Worth</h2>
    <ul>
      <li><strong>Total Assets:</strong> ${formatMoney(totalAssets)}</li>
      <li><strong>Total Liabilities:</strong> ${formatMoney(totalLiabilities)}</li>
      <li><strong>Net Worth:</strong> ${formatMoney(netWorth)}</li>
    </ul>

    <h2>💳 Liability Breakdown</h2>
    <ul>
      <li><strong>Loans Outstanding:</strong> ${formatMoney(totalLoanOutstanding)}</li>
      <li><strong>Credit Card Dues:</strong> ${formatMoney(totalCCOutstanding)}</li>
      <li><strong>Monthly EMI Commitment:</strong> ${formatMoney(currentMonthEmis)}</li>
    </ul>

    <h2>🎯 Goals Progress</h2>
    <ul>
      ${goals.map(g => `
        <li>
          <strong>${g.name}:</strong> ${formatMoney(g.current_amount)} / ${formatMoney(g.target_amount)} 
          (${Math.round((g.current_amount / g.target_amount) * 100)}%)
        </li>
      `).join('')}
    </ul>
    
    <p><em>Generated by Finance Tracker</em></p>
  `

    const textSummary = `
Daily Financial Summary (${new Date().toLocaleDateString('en-IN')})
---------------------------------------
Net Worth: ${formatMoney(netWorth)}
(Assets: ${formatMoney(totalAssets)} - Liabilities: ${formatMoney(totalLiabilities)})

Liabilities:
- Loans: ${formatMoney(totalLoanOutstanding)}
- Credit Cards: ${formatMoney(totalCCOutstanding)}
- Monthly EMI: ${formatMoney(currentMonthEmis)}

Goals:
${goals.map(g => `- ${g.name}: ${Math.round((g.current_amount / g.target_amount) * 100)}%`).join('\n')}
  `

    return { html: emailHtml, text: textSummary }
}
